version: '3'

services:
  h1:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image:
      244b
    volumes:
      - .:/usr/local/src/hbbft-wallet
    networks:
      app_net:
        ipv4_address: 172.16.238.2
    command: ./run.sh 4 1 0 1
  h2:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image:
      244b
    volumes:
      - .:/usr/local/src/hbbft-wallet
    networks:
      app_net:
        ipv4_address: 172.16.238.3
    command: ./run.sh 4 1 1 1
  h3:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image:
      244b
    volumes:
      - .:/usr/local/src/hbbft-wallet
    networks:
      app_net:
        ipv4_address: 172.16.238.4
    command: ./run.sh 4 1 2 1
  h4:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image:
      244b
    volumes:
      - .:/usr/local/src/hbbft-wallet
    networks:
      app_net:
        ipv4_address: 172.16.238.5
    command: ./run.sh 4 1 3 1
  client:
    container_name: hbbft_cl
    image:
      244b
    volumes:
      - .:/usr/local/src/hbbft-wallet
    networks:
      app_net:
        ipv4_address: 172.16.238.6
    command: python test/test_user_service_client.py
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24