version: '3'

services:
  h1:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image:
      244b
    volumes:
      - .:/usr/local/src/hbbft-wallet
    networks:
      app_net:
        ipv4_address: 172.16.238.2
    command: python server.py 4 1 0 thsigN_t.keys thencN_t.keys
  h2:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image:
      244b
    volumes:
      - .:/usr/local/src/hbbft-wallet
    networks:
      app_net:
        ipv4_address: 172.16.238.3
    command: python server.py 4 1 1 thsigN_t.keys thencN_t.keys
  h3:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image:
      244b
    volumes:
      - .:/usr/local/src/hbbft-wallet
    networks:
      app_net:
        ipv4_address: 172.16.238.4
    command: python server.py 4 1 2 thsigN_t.keys thencN_t.keys
  h4:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image:
      244b
    volumes:
      - .:/usr/local/src/hbbft-wallet
    networks:
      app_net:
        ipv4_address: 172.16.238.5
    command: python server.py 4 1 3 thsigN_t.keys thencN_t.keys
  client:
    container_name: hbbft_cl
    image:
      244b
    volumes:
      - .:/usr/local/src/hbbft-wallet
    networks:
      app_net:
        ipv4_address: 172.16.238.6
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1